### ISSUE TITLE
Custom File Associations

### ISSUE THREAD

**Issue by erohtar** [adirh3/Fluent-Search#457]
**Is your feature request related to a problem? Please describe.**
So one of the many better things that MS shat all over from previous Windows versions is file associations. They were much better and they were straightforward to use. 
Thankfully, I use XYplorer and it has custom file associations that are super easy to configure so I don't have to mess with whatever hell MS decided to force on us. 
Here's my config, and adding/updating it is just as easy it looks:
![image](https://user-images.githubusercontent.com/5120628/149785291-408e765e-750f-4d72-af21-a451a0451836.png)

BUT - when I launch any file using FS, it (understandably) launches with Windows file association, which is a problem for me because they're almost always wrong and not what I expect would open - as a solution, I just open the folder from FS into XY and open my file from there - not ideal, as you might imagine.

**Describe the solution you'd like**
FS should allow a way to customize file associations just like XY does. 

@Metroid-Prime , as an XYplorer user, you probably have used custom file associations and can relate with my problem here.

**Comment by adirh3** [comment]
@erohtar is there command line argument to open file through XYPlorer, might as well just let you use it to launch files through FS

**Comment by erohtar** [comment]
@adirh3, you read my mind there mate! I was just hoping it should be something where I don't have to create the same associations in two different apps!
While I check the command line arguments, here's another option - directly read XY's file associations from its INI:
![image](https://user-images.githubusercontent.com/5120628/149787436-680c8802-11cf-436f-8e55-41023d5bf8ce.png)

**Comment by adirh3** [comment]
> @adirh3, you read my mind there mate! I was just hoping it should be something where I don't have to create the same associations in two different apps! While I check the command line arguments, here's another option - directly read XY's file associations from its INI: ![image](https://user-images.githubusercontent.com/5120628/149787436-680c8802-11cf-436f-8e55-41023d5bf8ce.png)



> I think I found something! There's no direct cmd line switch for it, **BUT** XY brilliantly provides scripting support and you can launch a script from the command line: ![image](https://user-images.githubusercontent.com/5120628/149788813-2417f01f-fc6a-42be-8086-2d32ccefd6c0.png)
> 
> So I'm hoping FS can run XY with a script that launches the file with its custom file association :)

I will think about adding support for executing files with as a parameter for other EXE.
But in general, I recommend you try to write a script that takes that INI file and copy it to Windows' registry, as this is an issue you will experience with any app that opens file, not only FS.
Obviously you can't expect them all to support this.

**Comment by adirh3** [comment]
@erohtar btw you can already achieve it now using Tasks -
![image](https://user-images.githubusercontent.com/27368554/149790228-b759af91-5470-459c-87b9-621cc1832332.png)

**Comment by erohtar** [comment]
> I will think about adding support for executing files with as a parameter for other EXE.

Thank you sir!

> this is an issue you will experience with any app that opens file, not only FS. Obviously you can't expect them all to support this.

Yes of course, that's fully true - but I'm using using XY since it allows me to do that, and distancing myself from Listary as it doesn't allow me to do that, you can see where I'm headed lol. And also, as I'm spending so much time getting involved in making FS better (for me and everyone), I can hope that with it I'd get this feature.

> But in general, I recommend you try to write a script that takes that INI file and copy it to Windows' registry

You're right, and I could easily write such a script... but if I recall correctly, since Windows 8/10 hell started, the file associations get overwritten and changed on their own by the OS - whatever brain-eating bacteria led to such an outcome at MS, the file associations have to go through an install process to properly stick - am I wrong?

> btw you can already achieve it now using Tasks 

Neat! while I couldn't fully get it to work, this new 'Open file using' command showed at the very bottom of the list of File operations, while I'd need it to be the first option as the default launch for any file type.

**Comment by adirh3** [comment]
> Neat! while I couldn't fully get it to work, this new 'Open file using' command showed at the very bottom of the list of File operations, while I'd need it to be the first option as the default launch for any file type.

You can put key gesture `Enter` for the `Open file using` operation, that way it will trigger on Enter

**Comment by erohtar** [comment]
> You can put key gesture Enter (or any other) for the Open file using operation, that way it will trigger on Enter

Oh right! So right now using that it's trying to launch file but nothing happens, and the FS window doesn't go away either. What do I need to change these to:
![image](https://user-images.githubusercontent.com/5120628/149794937-a508b318-93e7-41ff-87ca-0585893e7a29.png)

I was guessing I'd get some errors and would have to fiddle with the quotes here:
![image](https://user-images.githubusercontent.com/5120628/149795129-3c792f4b-2ade-4838-af57-669a91e786f4.png)
but no errors or nothing..

**Comment by adirh3** [comment]
> > You can put key gesture Enter (or any other) for the Open file using operation, that way it will trigger on Enter
> 
> Oh right! So right now using that it's trying to launch file but nothing happens, and the FS window doesn't go away either. What do I need to change these to: ![image](https://user-images.githubusercontent.com/5120628/149794937-a508b318-93e7-41ff-87ca-0585893e7a29.png)
> 
> I was guessing I'd get some errors and would have to fiddle with the quotes here: ![image](https://user-images.githubusercontent.com/5120628/149795129-3c792f4b-2ade-4838-af57-669a91e786f4.png) but no errors or nothing..

Move the arguments to the arguments field

**Comment by erohtar** [comment]
Duh! you're right, silly of me.
The operation is now receiving just the file name though "fox.jpg" not the whole path. Is it supposed to be filePath.something?

**Comment by erohtar** [comment]
Btw I'm having to edit the text in notepad and paste it here because that bug with field size is still there:
![image](https://user-images.githubusercontent.com/5120628/149797097-a3f3191f-02c7-4124-bc71-f7f557cd3524.png)

**Comment by adirh3** [comment]
> Duh! you're right, silly of me. The operation is now receiving just the file name though "fox.jpg" not the whole path. Is it supposed to be filePath.something?

You need to call `result.Context` to get the file path

**Comment by erohtar** [comment]
Sorry, I'm still not getting a hang of working with FS tasks - tried a lot of things and got so many errors..

I've created an AHK script that perfectly reads the associated app for the extension of file name passed as first argument, and launches it with custom app. If no association is found, it's launched with default app.

From command line, I can run it as:
E:\Portables\FluentSearch\Blast\Scripts\Open_With_Custom.ahk C:\layout.xml
(with C:\layout.xml being an example file to be launched)

Now how do I configure a task to launch it when I press Enter on this file in search results?

This is what I have right now:

```
zoom: 1.0367999999999999
offsetX: 819.09440000000018
offsetY: 763.36320000000012
children:
- id: 0
  type: Result selector
  model:
    name:
      text: ''
      textMatchType: Contains
      matchCase: false
    type:
      text: File
      textMatchType: Contains
      matchCase: false
    searchApp:
      text: ''
      textMatchType: Contains
      matchCase: false
    context:
      text: ''
      textMatchType: Contains
      matchCase: false
  position:
    x: 93
    y: 398
  variables:
  - name: searchResult
    value: result
  children:
  - id: 1
    type: Custom operation
    model:
      name: Open With Custom
      iconGlyph: 
      keyGesture: Return
    position:
      x: 328
      y: 406
    variables:
    - name: myvar
      value: result
    children:
    - id: 2
      type: Open
      model:
        fileName: E:\Portables\FluentSearch\Blast\Scripts\Open_With_Custom.ahk
        runAsAdmin: false
        arguments: '{searchResult.context}'
      position:
        x: 549
        y: 474
      variables:
      - name: myvar
        value: result
      children: []
- id: 1
name: Open_With_Custom
iconGlyph: 
description: None
enable: true


```
